Repository skkuding/codedang, pull requests merged in 2023-11, with the labels that each got.

#950 fix(infra): keep env files in dev server
  .github/workflows/cd-dev.yml
Labels: 🪰 bug, ⛳️ team-infra

#956 fix(fe): removed sidebar items, fixed typo
  frontend/src/admin/pages/[groupId]/problem/index.vue
  frontend/src/common/components/Organism/Sidebar.vue
Labels: p1-chore 🧹, ⛳️ team-frontend

#959 feat(fe): client next.js scaffolding
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .prettierignore
  .prettierrc
  frontend-client/.eslintrc.js
  frontend-client/.gitignore
  frontend-client/app/contest/page.tsx
  frontend-client/app/favicon.ico
  frontend-client/app/globals.css
  frontend-client/app/group/page.tsx
  frontend-client/app/layout.tsx
  frontend-client/app/notice/page.tsx
  frontend-client/app/page.tsx
  frontend-client/app/problem/page.tsx
  frontend-client/next.config.js
  frontend-client/package.json
  frontend-client/postcss.config.js
  frontend-client/public/next.svg
  frontend-client/public/vercel.svg
  frontend-client/tailwind.config.ts
  frontend-client/tsconfig.json
  lefthook.yml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  skkuding.code-workspace
Labels: ⛳️ team-frontend, 💡 feature-client

#961 feat(be): change function name for updating user profile
  backend/apps/admin/src/group/group.service.spec.ts
  backend/apps/admin/src/group/group.service.ts
  backend/apps/admin/src/group/model/group.input.ts
  backend/apps/client/src/contest/contest.service.spec.ts
  backend/apps/client/src/group/mock/group.mock.ts
  backend/apps/client/src/notice/notice.service.spec.ts
  backend/apps/client/src/user/dto/update-userprofile.dto.ts
  backend/apps/client/src/user/user.controller.ts
  backend/apps/client/src/user/user.service.spec.ts
  backend/apps/client/src/user/user.service.ts
  backend/prisma/migrations/20231109131322_enable_user_deletion/migration.sql
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
Labels: ⛳️ team-backend, 💡 feature-client

#965 fix(fe): auth header is not added in local
  frontend/src/common/store/auth.ts
  frontend/vite.config.ts
Labels: 🪰 bug, ⛳️ team-frontend

#966 fix: migrate on checkout only in devcontainer
  scripts/post-checkout.sh
Labels: 🪰 bug

#967 fix: invalid post-checkout script
  scripts/post-checkout.sh
Labels: 🪰 bug

#982 fix(fe): fixed nav bar items order
  frontend/src/common/components/Organism/Header.vue
Labels: p1-chore 🧹

#971 feat(ci): parallelize build pipeline
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
  backend/.dockerignore
  backend/Dockerfile
  backend/entrypoint.sh
  infra/builder/api/Dockerfile.client
  infra/builder/api/entrypoint-client.sh
Labels: feat: ci

#984 fix(be): arg does not work in docker multi stage
  backend/Dockerfile
Labels: 🪰 bug, ⛳️ team-infra

#986 fix(infra): wrong docker dist directory
  backend/Dockerfile
Labels: 🪰 bug, ⛳️ team-infra

#987 fix(infra): include deploy out result in docker
  backend/Dockerfile
  backend/entrypoint.sh
Labels: 🪰 bug, ⛳️ team-infra

#988 feat(infra): execute setup script with docker compose
  .editorconfig
  .github/workflows/cd-dev.yml
  .vscode/settings.json
  Caddyfile
  backend/Dockerfile
  docker-compose.dev.yml
  docker-compose.yml
  docs/.vitepress/config.mts
  docs/project/deploy-pipeline.png
  docs/project/github-actions-runner.png
  docs/project/stage-server.md
  scripts/deploy.sh
Labels: ⛳️ team-infra

#897 feat(be): add github login
  .github/workflows/cd-prod.yml
  backend/apps/client/src/auth/auth.controller.ts
  backend/apps/client/src/auth/auth.module.ts
  backend/apps/client/src/auth/auth.service.ts
  backend/apps/client/src/auth/interface/social-user.interface.ts
  backend/apps/client/src/user/dto/social-signup.dto.ts
  backend/apps/client/src/user/enum/provider.enum.ts
  backend/apps/client/src/user/user.controller.ts
  backend/apps/client/src/user/user.service.ts
  backend/libs/auth/src/github/github.strategy.ts
  backend/libs/auth/src/jwt/jwt-auth.service.ts
  backend/libs/constants/src/oauth.constants.ts
  backend/package.json
  backend/prisma/migrations/20230925075957_add_user_oauth_model/migration.sql
  backend/prisma/migrations/20231102152425_make_email_not_null/migration.sql
  backend/prisma/schema.prisma
  infra/deploy/main.tf
  infra/deploy/variable.tf
  infra/local/main.tf
  infra/local/variable.tf
  infra/modules/codedang-infra/backend/client-task-definition.tftpl
  infra/modules/codedang-infra/ecs-api-client.tf
  infra/modules/codedang-infra/variables.tf
  pnpm-lock.yaml
Labels: ⛳️ team-backend
